# Generated by Django 4.2.9 on 2024-01-25 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300)),
                ('department', models.CharField(max_length=300)),
                ('join_date', models.DateTimeField()),
                ('profile_photo', models.CharField(max_length=300)),
            ],
        ),
    ]
